### PR TITLE
Download CSV data

### PR DESCRIPTION
**Pull request by shinyichen**
For each metrics and histogram, provided download button to download corresponding CSV data.
Screen Shot 2021-06-21 at 3 30 45 PM
Screen Shot 2021-06-21 at 3 31 29 PM

### CODE REVIEW

**Review by thostetler — CHANGES_REQUESTED** [review]
Instead of using `<i>` tags with a listener, can we switch to a `<button>` with the icon inside

Something like this:
```
<button class="btn btn-link download">
  <i class="fa-download ..." aria-hidden="true"></i>
  <span class="sr-only">download data</span>
</button>
```
which would have better accessibility

**Comment by shinyichen** [comment]
It's been updated as suggested.

> Instead of using `<i>` tags with a listener, can we switch to a `<button>` with the icon inside
> 
> Something like this:
> 
> ```
> <button class="btn btn-link download">
>   <i class="fa-download ..." aria-hidden="true"></i>
>   <span class="sr-only">download data</span>
> </button>
> ```
> 
> which would have better accessibility

**Comment by shinyichen** [comment]
@thostetler Now it's ready for review

**Review by thostetler — APPROVED** [review]
This LGTM, there may be a better way to do the actual download part.  I'm not positive if this style of adding attributes to a button and clicking is fully cross-browser -- but for now, I think this will work fine.

**Pull request merged**
