### PR TITLE
2 orcid issues addressed

### PR DESCRIPTION
**Pull request by aholachek**
I'm not going to lie, I'm not positive I solved the display issue.
But I made the Orcid Mode header darker, so it looks nicer at the cost of conspicuousness.

### CODE REVIEW

**Comment by romanchyla** [comment]
here is how i see it
bbb

**Comment by aholachek** [comment]
Ok well I think it looks very artistic that way, no?

No, I will try to figure it out.

**Comment by aholachek** [comment]
Oh wait I think I found it..I will fix it and send it to you after class.

**Comment by romanchyla** [comment]
bingo!

**Pull request merged**
